<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCNuihvi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCNuihvi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCNuihvi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCNuihvi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCNuihvi\App_KernelDevDebugContainer([
    'container.build_hash' => 'CNuihvi',
    'container.build_id' => 'd3421755',
    'container.build_time' => 1735262363,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCNuihvi');
